import React, { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { router } from 'expo-router';
import { supabase } from '../lib/supabase';

export default function BulkOrder(){const [itemType,setItemType]=useState('');const [quantity,setQuantity]=useState('1');const [neededBy,setNeededBy]=useState('');const [photo,setPhoto]=useState<ImagePicker.ImagePickerAsset|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 async function choosePhoto(){const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.7});if(!r.canceled)setPhoto(r.assets[0])}
 async function submit(){setError('');setLoading(true);try{let path:string|null=null;if(photo){const {data:user}=await supabase.auth.getUser();if(!user.user)throw new Error('Please sign in again');const ext=photo.fileName?.split('.').pop()||'jpg';path=`${user.user.id}/${crypto.randomUUID()}.${ext}`;const blob=await (await fetch(photo.uri)).blob();const {error:e}=await supabase.storage.from('bulk-order-photos').upload(path,blob,{contentType:photo.mimeType||'image/jpeg',upsert:false});if(e)throw e}const {error:e}=await supabase.rpc('create_bulk_order',{p_item_type:itemType,p_quantity:Number(quantity),p_lat:8.9806,p_lng:38.7578,p_needed_by:neededBy,p_photo_path:path,p_delivery_label:'Selected on app'});if(e)throw e;router.back()}catch(e){setError(e instanceof Error?e.message:'Could not submit order')}finally{setLoading(false)}}
 return <View style={styles.screen}><Text style={styles.title}>Bulk Order</Text><Text style={styles.subtitle}>Tell us what you need and when it should arrive.</Text><TextInput style={styles.input} value={itemType} onChangeText={setItemType} placeholder="Item type" accessibilityLabel="Item type"/><TextInput style={styles.input} value={quantity} onChangeText={setQuantity} placeholder="Quantity" keyboardType="number-pad" accessibilityLabel="Quantity"/><TextInput style={styles.input} value={neededBy} onChangeText={setNeededBy} placeholder="Needed by (YYYY-MM-DD)" accessibilityLabel="Needed by date"/><Pressable style={styles.secondary} onPress={choosePhoto}><Text style={styles.secondaryText}>{photo?'Photo selected':'Add item photo'}</Text></Pressable>{error&&<Text style={styles.error}>{error}</Text>}<Pressable style={styles.button} disabled={loading} onPress={submit}>{loading?<ActivityIndicator color="#fff"/>:<Text style={styles.buttonText}>Submit request</Text>}</Pressable></View>}
const styles=StyleSheet.create({screen:{flex:1,padding:22,backgroundColor:'#F7FAFC'},title:{fontSize:30,fontWeight:'900',color:'#0B1F33',marginTop:30},subtitle:{color:'#64748B',fontSize:16,marginTop:8,marginBottom:22},input:{height:52,backgroundColor:'#fff',borderWidth:1,borderColor:'#D9E1E8',borderRadius:14,paddingHorizontal:14,marginBottom:12},secondary:{minHeight:50,borderWidth:1,borderColor:'#B8C6D1',borderRadius:14,alignItems:'center',justifyContent:'center'},secondaryText:{fontWeight:'800',color:'#0B1F33'},button:{minHeight:52,borderRadius:14,backgroundColor:'#0F766E',alignItems:'center',justifyContent:'center',marginTop:14},buttonText:{color:'#fff',fontWeight:'800'},error:{color:'#B42318',marginTop:10}});
