import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import Mapbox from '@rnmapbox/maps';
import { useLocalSearchParams, router } from 'expo-router';
import { supabase } from '../../lib/supabase';
Mapbox.setAccessToken(process.env.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN ?? '');

type Trip={id:string;state:string;pickup:any;destination:any;driver_id:string|null;fare_base_minor:number;fare_distance_minor:number;fare_time_minor:number;promo_discount_minor:number;driver_addon_minor:number;total_minor:number};
type Driver={id:string;location:{coordinates:[number,number]}|null};
export default function TripScreen(){
 const {id}=useLocalSearchParams<{id:string}>(); const [trip,setTrip]=useState<Trip|null>(null); const [driver,setDriver]=useState<Driver|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [flagging,setFlagging]=useState(false);
 useEffect(()=>{if(!id)return;let tripChannel:any;let driverChannel:any;(async()=>{try{const {data,error:e}=await supabase.from('trips').select('*').eq('id',id).single();if(e)throw e;setTrip(data as Trip);if(data.driver_id){const {data:d}=await supabase.from('drivers').select('id,location').eq('id',data.driver_id).single();setDriver(d as Driver)}tripChannel=supabase.channel(`trip-${id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'trips',filter:`id=eq.${id}`},payload=>setTrip(payload.new as Trip)).subscribe();if(data.driver_id){driverChannel=supabase.channel(`driver-${data.driver_id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'drivers',filter:`id=eq.${data.driver_id}`},payload=>setDriver(payload.new as Driver)).subscribe()}}catch(e){setError(e instanceof Error?e.message:'Unable to load trip')}finally{setLoading(false)}})();return()=>{if(tripChannel)supabase.removeChannel(tripChannel);if(driverChannel)supabase.removeChannel(driverChannel)}},[id]);
 async function flagAddon(){setFlagging(true);try{const {data:addon}=await supabase.from('addon_fees').select('id').eq('trip_id',id).eq('status','pending').order('created_at',{ascending:false}).limit(1).maybeSingle();if(!addon)throw new Error('No pending add-on fee to flag');const {error:e}=await supabase.from('addon_fees').update({status:'flagged'}).eq('id',addon.id);if(e)throw e}catch(e){setError(e instanceof Error?e.message:'Could not flag fee')}finally{setFlagging(false)}}
 if(loading)return <View style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Loading trip…</Text></View>; if(error&&!trip)return <View style={styles.center}><Text style={styles.error}>{error}</Text><Pressable onPress={()=>router.back()}><Text style={styles.link}>Go back</Text></Pressable></View>; if(!trip)return null;
 const pickup=trip.pickup?.coordinates as [number,number]|undefined; const destination=trip.destination?.coordinates as [number,number]|undefined; const driverCoords=driver?.location?.coordinates;
 return <View style={styles.screen}><View style={styles.map}><Mapbox.MapView style={StyleSheet.absoluteFill} styleURL={Mapbox.StyleURL.Street}><Mapbox.Camera zoomLevel={13} centerCoordinate={driverCoords??pickup??[38.7578,8.9806]}/>{pickup&&<Mapbox.PointAnnotation id="pickup" coordinate={pickup}/>} {destination&&<Mapbox.PointAnnotation id="destination" coordinate={destination}/>} {driverCoords&&<Mapbox.PointAnnotation id="driver" coordinate={driverCoords}/>}</Mapbox.MapView></View><View style={styles.sheet}><Text style={styles.status}>{trip.state.replace('_',' ').toUpperCase()}</Text><Text style={styles.title}>{trip.driver_id?'Your driver is on the way':'Finding your driver'}</Text><View style={styles.receipt}><Text style={styles.receiptTitle}>Receipt</Text><Row label="Base" value={trip.fare_base_minor}/><Row label="Distance" value={trip.fare_distance_minor}/><Row label="Time" value={trip.fare_time_minor}/><Row label="Promo" value={-trip.promo_discount_minor}/><Row label="Driver add-ons" value={trip.driver_addon_minor}/><View style={styles.total}><Text style={styles.totalLabel}>Total</Text><Text style={styles.totalValue}>{trip.total_minor.toLocaleString()} ETB</Text></View></View>{trip.driver_addon_minor>0&&<Pressable disabled={flagging} onPress={flagAddon} style={styles.secondary}><Text style={styles.secondaryText}>{flagging?'Flagging…':'Flag driver add-on for review'}</Text></Pressable>}{error&&<Text style={styles.error}>{error}</Text>}</View></View>
}
function Row({label,value}:{label:string,value:number}){return <View style={styles.row}><Text style={styles.muted}>{label}</Text><Text style={styles.rowValue}>{value.toLocaleString()} ETB</Text></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#F7FAFC'},map:{flex:1},sheet:{backgroundColor:'#fff',borderTopLeftRadius:24,borderTopRightRadius:24,padding:18,paddingBottom:26},status:{fontSize:11,fontWeight:'800',letterSpacing:1.2,color:'#0F766E'},title:{fontSize:23,fontWeight:'800',color:'#0B1F33',marginTop:4},receipt:{marginTop:14,padding:14,borderRadius:16,backgroundColor:'#F6F8FA'},receiptTitle:{fontSize:15,fontWeight:'800',color:'#0B1F33',marginBottom:8},row:{flexDirection:'row',justifyContent:'space-between',paddingVertical:5},rowValue:{fontWeight:'700',color:'#0B1F33'},total:{borderTopWidth:1,borderTopColor:'#D9E1E8',marginTop:8,paddingTop:10,flexDirection:'row',justifyContent:'space-between'},totalLabel:{fontWeight:'800',color:'#0B1F33'},totalValue:{fontSize:18,fontWeight:'900',color:'#0F766E'},secondary:{minHeight:48,borderRadius:12,borderWidth:1,borderColor:'#B8C6D1',alignItems:'center',justifyContent:'center',marginTop:12},secondaryText:{fontWeight:'800',color:'#0B1F33'},muted:{color:'#64748B'},error:{color:'#B42318',marginTop:8},link:{color:'#0F766E',fontWeight:'800',marginTop:14},center:{flex:1,justifyContent:'center',alignItems:'center',padding:24}}
);
