import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import Mapbox from '@rnmapbox/maps';
import { router } from 'expo-router';
import { calculateFare, type FareConfig } from '@driver-super-app/shared';
import { supabase } from '../../lib/supabase';
import { MapboxMapsProvider, type Coordinates } from '../../providers/maps';

const ADDIS: Coordinates = { latitude: 8.9806, longitude: 38.7578 };
Mapbox.setAccessToken(process.env.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN ?? '');

export default function Home() {
  const [pickup,setPickup]=useState<Coordinates>(ADDIS);
  const [destination,setDestination]=useState<Coordinates>({latitude:8.99,longitude:38.77});
  const [selecting,setSelecting]=useState<'pickup'|'destination'>('pickup');
  const [fareConfig,setFareConfig]=useState<FareConfig|null>(null);
  const [estimate,setEstimate]=useState<{distanceM:number;durationS:number}|null>(null);
  const [promo,setPromo]=useState('');
  const [loading,setLoading]=useState(true);
  const [requesting,setRequesting]=useState(false);
  const [error,setError]=useState('');

  useEffect(()=>{(async()=>{try{const {data:profile}=await supabase.from('profiles').select('city_id').single();if(!profile?.city_id) throw new Error('Choose a city in your profile first');const {data:config,error:e}=await supabase.from('fare_configs').select('base_minor,per_km_minor,per_minute_minor,minimum_fare_minor').eq('city_id',profile.city_id).eq('service_type','taxi').eq('is_active',true).order('effective_from',{ascending:false}).limit(1).single();if(e)throw e;if(!config)throw new Error('Fare configuration unavailable');setFareConfig({baseMinor:Number(config.base_minor),perKmMinor:Number(config.per_km_minor),perMinuteMinor:Number(config.per_minute_minor),minimumFareMinor:Number(config.minimum_fare_minor)})}catch(e){setError(e instanceof Error?e.message:'Unable to load fare configuration')}finally{setLoading(false)}})()},[]);
  useEffect(()=>{const provider=new MapboxMapsProvider();provider.estimateRoute(pickup,destination).then(setEstimate).catch(()=>setEstimate(null))},[pickup,destination]);
  const fare=useMemo(()=>estimate&&fareConfig?calculateFare(fareConfig,{distanceKm:estimate.distanceM/1000,durationMinutes:estimate.durationS/60}):null,[estimate,fareConfig]);
  function mapPress(e:any){const [longitude,latitude]=e.geometry.coordinates as [number,number];const point={latitude,longitude};selecting==='pickup'?setPickup(point):setDestination(point)}
  async function requestRide(){setError('');if(!estimate||!fare){setError('Waiting for route estimate');return}setRequesting(true);try{const {data,error:e}=await supabase.rpc('create_trip_request',{p_service_type:'taxi',p_pickup_lat:pickup.latitude,p_pickup_lng:pickup.longitude,p_destination_lat:destination.latitude,p_destination_lng:destination.longitude,p_distance_m:estimate.distanceM,p_duration_s:estimate.durationS,p_promo_code:promo.trim()||null});if(e)throw e;if(!data)throw new Error('Trip was not created');router.push(`/trip/${data.id}`)}catch(e){setError(e instanceof Error?e.message:'Could not request ride')}finally{setRequesting(false)}}
  if(loading)return <View style={styles.center}><ActivityIndicator size="large"/><Text style={styles.muted}>Preparing your ride…</Text></View>;
  return <View style={styles.screen}><View style={styles.mapWrap}><Mapbox.MapView style={StyleSheet.absoluteFill} styleURL={Mapbox.StyleURL.Street} onPress={mapPress} accessibilityLabel="Ride request map"><Mapbox.Camera zoomLevel={13} centerCoordinate={[pickup.longitude,pickup.latitude]}/><Mapbox.PointAnnotation id="pickup" coordinate={[pickup.longitude,pickup.latitude]}/><Mapbox.PointAnnotation id="destination" coordinate={[destination.longitude,destination.latitude]}/></Mapbox.MapView></View><View style={styles.sheet}><Text style={styles.title}>Where to?</Text><View style={styles.switch}><Pressable onPress={()=>setSelecting('pickup')} style={[styles.chip,selecting==='pickup'&&styles.active]}><Text style={styles.chipText}>Pickup</Text></Pressable><Pressable onPress={()=>setSelecting('destination')} style={[styles.chip,selecting==='destination'&&styles.active]}><Text style={styles.chipText}>Destination</Text></Pressable></View><Text style={styles.hint}>Tap the map to set {selecting}.</Text>{fare&&<View style={styles.fare}><Text style={styles.fareLabel}>Estimated fare</Text><Text style={styles.fareValue}>{fare.totalMinor.toLocaleString()} ETB</Text><Text style={styles.muted}>{((estimate?.distanceM??0)/1000).toFixed(1)} km · {Math.ceil((estimate?.durationS??0)/60)} min</Text></View>}<TextInput value={promo} onChangeText={setPromo} placeholder="Promo code (optional)" autoCapitalize="characters" style={styles.input} accessibilityLabel="Promo code"/>{!!error&&<Text accessibilityRole="alert" style={styles.error}>{error}</Text>}<Pressable disabled={requesting} onPress={requestRide} style={styles.button}>{requesting?<ActivityIndicator color="#fff"/>:<Text style={styles.buttonText}>Confirm ride</Text>}</Pressable></View></View>
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#F7FAFC'},mapWrap:{flex:1},sheet:{backgroundColor:'#fff',borderTopLeftRadius:24,borderTopRightRadius:24,padding:18,paddingBottom:26},title:{fontSize:24,fontWeight:'800',color:'#0B1F33'},switch:{flexDirection:'row',gap:8,marginTop:12},chip:{paddingHorizontal:16,paddingVertical:10,borderRadius:999,backgroundColor:'#EEF2F5'},active:{backgroundColor:'#D8F1EE'},chipText:{fontWeight:'700',color:'#0B1F33'},hint:{color:'#64748B',marginTop:8},fare:{marginTop:14,padding:14,borderRadius:16,backgroundColor:'#F4F8F8'},fareLabel:{fontSize:12,color:'#64748B'},fareValue:{fontSize:24,fontWeight:'800',color:'#0F766E',marginVertical:2},muted:{color:'#64748B',marginTop:4},input:{height:48,borderWidth:1,borderColor:'#D9E1E8',borderRadius:12,paddingHorizontal:14,marginTop:12},button:{minHeight:52,backgroundColor:'#0F766E',borderRadius:14,alignItems:'center',justifyContent:'center',marginTop:12},buttonText:{color:'#fff',fontWeight:'800',fontSize:16},error:{color:'#B42318',marginTop:8},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24}});
