import React,{useEffect,useRef,useState}from'react';
import{Linking,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import MapView,{Marker,Polyline,Region}from'react-native-maps';
import*as Location from'expo-location';
import{createClient,Session}from'@supabase/supabase-js';
const url=process.env.EXPO_PUBLIC_SUPABASE_URL??'';const key=process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY??'';const db=createClient(url,key);const NAVY='#0B1F33',TEAL='#0F766E',BG='#F6F8FA',RED='#DC2626',GREEN='#16A34A';
const money=(n:number)=>`${Math.round(n/100).toLocaleString()} Birr`;const phone=(x:string)=>{const d=x.replace(/\D/g,'');return d.startsWith('251')?`+${d}`:d.startsWith('0')?`+251${d.slice(1)}`:`+251${d}`};const pt=(x:any)=>x?.coordinates?{latitude:x.coordinates[1],longitude:x.coordinates[0]}:null;const id=()=>crypto.randomUUID?.()??'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:r&3|8;return v.toString(16)});
type Trip={id:string;city_id:string;customer_id:string|null;driver_id:string|null;state:string;pickup:any;destination:any;pickup_label:string|null;destination_label:string|null;total_minor:number};type P={id:string;passenger_index:number;phone:string;status:string;pickup:any;destination:any;trip_id:string;onboard_distance_m?:number;onboard_duration_s?:number};type Opt={id:string;amount_minor:number};
export default function App(){const[s,setS]=useState<Session|null>(null),[tab,setTab]=useState('home'),[online,setOnline]=useState(false),[loc,setLoc]=useState<Location.LocationObject|null>(null),[req,setReq]=useState<Trip[]>([]),[trip,setTrip]=useState<Trip|null>(null),[ps,setPs]=useState<P[]>([]),[opts,setOpts]=useState<Opt[]>([]),[earn,setEarn]=useState(0),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState({phone:'',pl:'',pg:'',dl:'',dg:''});const[sub,setSub]=useState<Location.LocationSubscription|null>(null);const[channel]=useState(()=>db.channel('driver-realtime'));const[timer,setTimer]=useState(0);const interval=useRef<any>();
useEffect(()=>{if(!url||!key){setMsg('Supabase environment variables are missing.');return}db.auth.getSession().then(({data})=>setS(data.session));const x=db.auth.onAuthStateChange((_e,v)=>setS(v));return()=>x.data.subscription.unsubscribe()},[]);
useEffect(()=>{if(!s)return;load();channel.on('postgres_changes',{event:'*',schema:'public',table:'trips'},load).on('postgres_changes',{event:'*',schema:'public',table:'addon_fees'},p=>{if((p.new as any)?.trip_id===trip?.id)setMsg('Add-on updated for the customer.')}).subscribe();return()=>{channel.unsubscribe();sub?.remove()}},[s]);
useEffect(()=>{if(timer>0)interval.current=setInterval(()=>setTimer(x=>Math.max(0,x-1)),1000);return()=>clearInterval(interval.current)},[timer]);
useEffect(()=>{if(!online||!s){sub?.remove();return}startGps();return()=>sub?.remove()},[online,s]);
async function load(){const[{data:r},{data:o},{data:e}]=await Promise.all([db.from('trips').select('*').eq('state','requested').is('driver_id',null).order('requested_at').limit(10),db.from('addon_fees').select('id,amount_minor').eq('status','option').order('amount_minor'),db.from('trips').select('total_minor').eq('driver_id',s!.user.id).eq('state','completed')]);if(r)setReq(r as Trip[]);if(o)setOpts(o as Opt[]);setEarn((e??[]).reduce((a:any,x:any)=>a+Number(x.total_minor||0),0))}
async function startGps(){const p=await Location.requestForegroundPermissionsAsync();if(p.status!=='granted'){setOnline(false);setMsg('Location permission is required while online.');return}const driver=(await db.from('drivers').select('city_id').eq('id',s!.user.id).single()).data;setSub(await Location.watchPositionAsync({accuracy:Location.Accuracy.High,distanceInterval:10,timeInterval:5000},async l=>{setLoc(l);if(driver?.city_id)await db.from('driver_locations').upsert({driver_id:s!.user.id,city_id:driver.city_id,location:`POINT(${l.coords.longitude} ${l.coords.latitude})`,heading:l.coords.heading,speed_mps:l.coords.speed,accuracy_m:l.coords.accuracy,updated_at:new Date().toISOString()},{onConflict:'driver_id'})}))}
async function accept(t:Trip){setBusy(true);const{data,error}=await db.from('trips').update({driver_id:s!.user.id,state:'accepted',accepted_at:new Date().toISOString()}).eq('id',t.id).eq('state','requested').is('driver_id',null).select().single();setBusy(false);if(error)setMsg(error.message);else{setTrip(data as Trip);setReq(req.filter(x=>x.id!==t.id));setTimer(0)}}
async function state(v:string){if(!trip)return;setBusy(true);const patch:any={state:v};if(v==='completed')patch.completed_at=new Date().toISOString();if(v==='cancelled')patch.cancelled_at=new Date().toISOString();const{data,error}=await db.from('trips').update(patch).eq('id',trip.id).eq('driver_id',s!.user.id).select().single();setBusy(false);if(error)setMsg(error.message);else{setTrip(data as Trip);setMsg(v==='completed'?'Trip completed.':'')}}
async function shared(){if(!trip)return;const{error}=await db.from('shared_rides').insert({city_id:trip.city_id,trip_id:trip.id,driver_id:s!.user.id,customer_id:trip.customer_id,state:'pending'});setMsg(error?.message??'Shared ride created. Add up to four passengers.')}
async function loadP(){if(!trip)return;const{data}=await db.from('shared_ride_passengers').select('*').eq('trip_id',trip.id).order('passenger_index');if(data)setPs(data as P[])}
async function addP(){if(!trip)return;if(ps.length>=4){setMsg('Maximum 4 passengers reached.');return}const f=form;if(!/^\+2519\d{8}$/.test(phone(f.phone))){setMsg('Enter a valid Ethiopian mobile number.');return}const n=[f.pl,f.pg,f.dl,f.dg].map(Number);if(n.some(Number.isNaN)){setMsg('Enter all four coordinates.');return}const{data:r}=await db.from('shared_rides').select('id').eq('trip_id',trip.id).eq('driver_id',s!.user.id).limit(1);if(!r?.[0]){setMsg('Create the shared ride first.');return}setBusy(true);const{data,error}=await db.rpc('add_shared_ride_passenger',{p_shared_ride_id:r[0].id,p_phone:phone(f.phone),p_pickup_lat:n[0],p_pickup_lng:n[1],p_destination_lat:n[2],p_destination_lng:n[3]});setBusy(false);if(error)setMsg(error.message);else{setPs([...ps,data as P]);setForm({phone:'',pl:'',pg:'',dl:'',dg:''});setMsg(ps.length===3?'Four-passenger limit reached.':'Passenger invited; confirmation is required before departure.')}}
async function finishP(p:P){const{error}=await db.rpc('complete_shared_passenger',{p_passenger_id:p.id,p_distance_m:p.onboard_distance_m??0,p_duration_s:p.onboard_duration_s??0});setMsg(error?.message??'Passenger fare finalized server-side.');loadP()}
async function addon(a:number){if(!trip)return;const{error}=await db.rpc('add_driver_addon',{p_trip_id:trip.id,p_amount_minor:a,p_idempotency_key:id(),p_lat:loc?.coords.latitude??null,p_lng:loc?.coords.longitude??null});setMsg(error?.message??`${money(a)} add-on added and sent to customer.`)}
const region:Region=loc?{latitude:loc.coords.latitude,longitude:loc.coords.longitude,latitudeDelta:.025,longitudeDelta:.025}:{latitude:9.03,longitude:38.74,latitudeDelta:.08,longitudeDelta:.08};const route=ps.flatMap(p=>[pt(p.pickup),pt(p.destination)]).filter(Boolean) as any[];
if(!s)return <SafeAreaView style={st.center}><Text style={st.title}>Driver sign-in</Text><Text style={st.muted}>Use the existing Supabase authenticated driver session.</Text></SafeAreaView>;
return <SafeAreaView style={st.screen}><View style={st.head}><View><Text style={st.kicker}>DRIVER</Text><Text style={st.title}>Drive</Text></View><Pressable accessibilityLabel="Online toggle" style={st.online} onPress={()=>setOnline(!online)}><View style={[st.dot,{backgroundColor:online?GREEN:'#64748B'}]}/><Text style={{fontWeight:'900',color:online?GREEN:NAVY}}>{online?'Online':'Offline'}</Text></Pressable></View>{msg?<View style={st.notice}><Text style={st.noticeText}>{msg}</Text></View>:null}
{tab==='home'?<ScrollView contentContainerStyle={st.content}><View style={st.map}><MapView style={{flex:1}} region={region} showsUserLocation><Marker coordinate={region} title="Driver"/>{trip&&pt(trip.pickup)?<Marker coordinate={pt(trip.pickup)!} title="Pickup"/>:null}{trip&&pt(trip.destination)?<Marker coordinate={pt(trip.destination)!} title="Destination"/>:null}{ps.map(p=><React.Fragment key={p.id}><Marker coordinate={pt(p.pickup)!} title={`P${p.passenger_index} pickup`}/><Marker coordinate={pt(p.destination)!} title={`P${p.passenger_index} dropoff`}/></React.Fragment>)}<Polyline coordinates={route} strokeColor={TEAL} strokeWidth={4}/></MapView><Pressable style={st.nav} onPress={()=>trip&&pt(trip.destination)&&Linking.openURL(`https://www.mapbox.com/directions/?destination=${pt(trip.destination)!.latitude},${pt(trip.destination)!.longitude}`)}><Text style={st.white}>Open Mapbox navigation</Text></Pressable></View>
{trip?<><View style={st.card}><Text style={st.section}>Current trip</Text><Text style={st.muted}>{trip.pickup_label??'Pickup'} → {trip.destination_label??'Destination'}</Text><View style={st.row}><Text style={st.status}>{trip.state.replace('_',' ')}</Text><Text style={st.amount}>{money(trip.total_minor||0)}</Text></View><View style={st.grid}><Btn t="Arriving" f={()=>state('arriving')} d={busy}/><Btn t="Start trip" f={()=>state('in_progress')} d={busy}/><Btn t="Complete" f={()=>state('completed')} d={busy}/><Btn t="Cancel" f={()=>state('cancelled')} danger d={busy}/></View></View>
<View style={st.card}><View style={st.row}><Text style={st.section}>Passengers {ps.length}/4</Text><Btn t="Refresh" f={loadP}/></View><Btn t="Start shared ride" f={shared}/>{ps.map(p=><View key={p.id} style={st.line}><Text style={st.section}>Passenger {p.passenger_index}</Text><Text style={st.muted}>{p.phone} · {p.status}</Text><Btn t="Finalize fare" f={()=>finishP(p)}/></View>)}{ps.length<4?<><TextInput style={st.input} value={form.phone} onChangeText={x=>setForm({...form,phone:x})} placeholder="9XXXXXXXX" keyboardType="phone-pad" accessibilityLabel="Passenger phone"/><View style={st.two}><TextInput style={st.input} value={form.pl} onChangeText={x=>setForm({...form,pl:x})} placeholder="Pickup lat" keyboardType="decimal-pad"/><TextInput style={st.input} value={form.pg} onChangeText={x=>setForm({...form,pg:x})} placeholder="Pickup lng" keyboardType="decimal-pad"/></View><View style={st.two}><TextInput style={st.input} value={form.dl} onChangeText={x=>setForm({...form,dl:x})} placeholder="Dropoff lat" keyboardType="decimal-pad"/><TextInput style={st.input} value={form.dg} onChangeText={x=>setForm({...form,dg:x})} placeholder="Dropoff lng" keyboardType="decimal-pad"/></View><Btn t="Add passenger" f={addP} d={busy}/></>:null}</View>
<View style={st.card}><Text style={st.section}>Quick add-on</Text><Text style={st.muted}>Loaded from Supabase. Server enforces the per-trip maximum.</Text><View style={st.grid}>{opts.map(o=><Btn key={o.id} t={`+${money(o.amount_minor)}`} f={()=>addon(o.amount_minor)}/>)}</View></View></>:req.length?<>{req.map(r=><View key={r.id} style={st.card}><Text style={st.section}>New request</Text><Text style={st.muted}>{r.pickup_label??'Pickup'} → {r.destination_label??'Destination'}</Text><Text style={st.amount}>{money(r.total_minor||0)}</Text><View style={st.two}><Btn t="Decline" danger f={()=>setReq(req.filter(x=>x.id!==r.id))}/><Btn t={timer?`Accept ${timer}s`:'Accept'} f={()=>{setTimer(30);accept(r)}}/></View></View>)}</>:<View style={st.empty}><Text style={st.section}>No requests</Text><Text style={st.muted}>{online?'Waiting for requests…':'Go online to receive requests.'}</Text></View>}</ScrollView>:tab==='earnings'?<ScrollView contentContainerStyle={st.content}><View style={st.hero}><Text style={st.kicker}>TODAY</Text><Text style={st.heroAmount}>{money(earn)}</Text><Text style={st.muted}>Completed trips</Text></View><Btn t="Refresh earnings" f={load}/></ScrollView>:<ScrollView contentContainerStyle={st.content}><View style={st.card}><Text style={st.section}>Driver account</Text><Text style={st.muted}>{s.user.phone??s.user.email??'Authenticated driver'}</Text><Text style={st.muted}>GPS publishing: {online?'active':'paused'}</Text></View><View style={st.card}><Text style={st.section}>Server controls</Text><Text style={st.muted}>Fares, passenger limits and add-on limits are enforced by Supabase RPCs. No secrets are bundled.</Text></View></ScrollView>}
<View style={st.tabs}>{['home','earnings','profile'].map(x=><Pressable key={x} accessibilityRole="tab" accessibilityState={{selected:tab===x}} style={st.tab} onPress={()=>setTab(x)}><Text style={[st.tabText,tab===x&&st.active]}>{x[0].toUpperCase()+x.slice(1)}</Text></Pressable>)}</View></SafeAreaView>}
function Btn({t,f,d,danger}:{t:string;f:()=>void;d?:boolean;danger?:boolean}){return <Pressable accessibilityRole="button" disabled={d} onPress={f} style={[st.btn,danger&&st.danger,d&&st.disabled]}><Text style={st.white}>{t}</Text></Pressable>}
const st=StyleSheet.create({screen:{flex:1,backgroundColor:BG},center:{flex:1,justifyContent:'center',alignItems:'center',padding:24,backgroundColor:BG},content:{padding:16,paddingBottom:105,gap:14},head:{backgroundColor:'#fff',padding:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{fontSize:12,fontWeight:'900',letterSpacing:1.5,color:TEAL},title:{fontSize:30,fontWeight:'900',color:NAVY},muted:{color:'#64748B',lineHeight:21},online:{minHeight:48,paddingHorizontal:14,borderRadius:24,backgroundColor:'#E2E8F0',flexDirection:'row',alignItems:'center',gap:8},dot:{width:9,height:9,borderRadius:5},notice:{margin:12,padding:12,borderRadius:12,backgroundColor:'#DFFAF5'},noticeText:{color:TEAL,fontWeight:'800'},map:{height:300,borderRadius:18,overflow:'hidden'},nav:{position:'absolute',left:12,right:12,bottom:12,minHeight:48,borderRadius:12,backgroundColor:NAVY,alignItems:'center',justifyContent:'center'},card:{backgroundColor:'#fff',borderRadius:18,padding:16,gap:12},section:{fontSize:18,fontWeight:'900',color:NAVY},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},status:{color:TEAL,fontWeight:'900',textTransform:'capitalize'},amount:{fontSize:20,fontWeight:'900',color:NAVY},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},btn:{minHeight:48,borderRadius:12,backgroundColor:TEAL,alignItems:'center',justifyContent:'center',paddingHorizontal:14,flexGrow:1},danger:{backgroundColor:RED},disabled:{opacity:.45},white:{color:'#fff',fontWeight:'900'},two:{flexDirection:'row',gap:10},input:{flex:1,minHeight:48,borderWidth:1,borderColor:'#CBD5E1',borderRadius:12,paddingHorizontal:12,backgroundColor:'#fff',fontSize:16},line:{borderTopWidth:1,borderTopColor:'#E2E8F0',paddingTop:10,gap:8},empty:{padding:24,alignItems:'center',gap:8},hero:{backgroundColor:NAVY,borderRadius:20,padding:24,gap:8},heroAmount:{fontSize:42,fontWeight:'900',color:'#fff'},tabs:{position:'absolute',bottom:0,left:0,right:0,height:82,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#E2E8F0',flexDirection:'row',paddingBottom:10},tab:{flex:1,alignItems:'center',justifyContent:'center',minHeight:48},tabText:{fontWeight:'800',color:'#94A3B8'},active:{color:TEAL}});
