import React,{useState}from'react';
import{Pressable,SafeAreaView,StyleSheet,Text,TextInput,View}from'react-native';
import{useRouter}from'expo-router';
import{createClient}from'@supabase/supabase-js';
const db=createClient(process.env.EXPO_PUBLIC_SUPABASE_URL??'',process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY??'');
export default function Auth(){const router=useRouter();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[name,setName]=useState('');const[signup,setSignup]=useState(false);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
async function submit(){setBusy(true);setMsg('');const result=signup?await db.auth.signUp({email:email.trim().toLowerCase(),password,options:{data:{full_name:name.trim()}}}):await db.auth.signInWithPassword({email:email.trim().toLowerCase(),password});setBusy(false);if(result.error){setMsg(result.error.message);return}if(signup&&!result.data.session){setMsg('Account created. Check your email to verify it.');return}router.replace('/')}
return <SafeAreaView style={s.screen}><View style={s.card}><Text style={s.kicker}>DRIVER SUPERAPP</Text><Text style={s.h1}>{signup?'Create account':'Welcome back'}</Text><Text style={s.muted}>{signup?'Create your customer account.':'Sign in to book a ride.'}</Text>{signup?<TextInput value={name}onChangeText={setName}placeholder="Full name"style={s.input}/>:null}<TextInput value={email}onChangeText={setEmail}placeholder="Email address"keyboardType="email-address"autoCapitalize="none"style={s.input}/><TextInput value={password}onChangeText={setPassword}placeholder="Password"secureTextEntry style={s.input}/><Pressable disabled={busy}style={s.btn}onPress={submit}><Text style={s.white}>{busy?'Please wait…':signup?'Create account':'Sign in'}</Text></Pressable>{msg?<Text style={s.notice}>{msg}</Text>:null}<Pressable onPress={()=>setSignup(!signup)}><Text style={s.link}>{signup?'Already have an account? Sign in':'New here? Create an account'}</Text></Pressable><Pressable onPress={()=>router.back()}><Text style={s.back}>Back</Text></Pressable></View></SafeAreaView>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F6F8FA',justifyContent:'center',padding:20},card:{backgroundColor:'#fff',borderRadius:24,padding:22,gap:13},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.5,color:'#0F766E'},h1:{fontSize:30,fontWeight:'900',color:'#0B1F33'},muted:{color:'#64748B',lineHeight:21},input:{minHeight:52,borderWidth:1,borderColor:'#D7DEE5',borderRadius:13,paddingHorizontal:14,fontSize:16},btn:{minHeight:52,borderRadius:14,backgroundColor:'#0F766E',alignItems:'center',justifyContent:'center'},white:{color:'#fff',fontWeight:'900'},notice:{color:'#0F766E',fontWeight:'800'},link:{color:'#0F766E',fontWeight:'900',textAlign:'center'},back:{color:'#64748B',fontWeight:'800',textAlign:'center'}});
