import React,{useEffect,useState}from'react';
import{Linking,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{createClient,Session}from'@supabase/supabase-js';
const url=process.env.EXPO_PUBLIC_SUPABASE_URL??'';const key=process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY??'';const db=createClient(url,key);
const TEAL='#0F766E',NAVY='#0B1F33',BG='#F6F8FA';
const money=(n:number)=>`${Math.round(n/100).toLocaleString()} Birr`;
export default function App(){
 const[s,setS]=useState<Session|null>(null),[tab,setTab]=useState('home'),[pickup,setPickup]=useState(''),[drop,setDrop]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[trip,setTrip]=useState<any>(null),[history,setHistory]=useState<any[]>([]);
 useEffect(()=>{if(!url||!key){setMsg('Supabase configuration is missing.');return}db.auth.getSession().then(({data})=>setS(data.session));const x=db.auth.onAuthStateChange((_e,v)=>setS(v));return()=>x.data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(s)load()},[s]);
 async function load(){const{data}=await db.from('trips').select('id,state,pickup_label,destination_label,total_minor,requested_at').eq('customer_id',s!.user.id).order('requested_at',{ascending:false}).limit(8);if(data){setHistory(data);setTrip(data.find(x=>['requested','accepted','arriving','in_progress'].includes(x.state))??null)}}
 async function requestRide(){if(!s){setMsg('Sign in to request a ride.');return}if(!pickup.trim()||!drop.trim()){setMsg('Enter pickup and destination.');return}setBusy(true);const{data,error}=await db.from('trips').insert({customer_id:s.user.id,state:'requested',pickup_label:pickup.trim(),destination_label:drop.trim(),total_minor:0}).select().single();setBusy(false);if(error)setMsg(error.message);else{setTrip(data);setMsg('Ride requested. Finding a nearby driver…');load()}}
 async function cancel(){if(!trip)return;const{error}=await db.from('trips').update({state:'cancelled'}).eq('id',trip.id).eq('customer_id',s!.user.id);setMsg(error?.message??'Ride cancelled.');load()}
 if(!s)return <SafeAreaView style={st.center}><Text style={st.logo}>FERES-STYLE MOBILITY</Text><Text style={st.h1}>Move around Addis.</Text><Text style={st.muted}>Sign in with your existing customer account to request rides.</Text><Pressable style={st.btn} onPress={()=>setMsg('Open the account flow from the customer app.') }><Text style={st.white}>Get started</Text></Pressable>{msg?<Text style={st.notice}>{msg}</Text>:null}</SafeAreaView>;
 return <SafeAreaView style={st.screen}>
  <View style={st.header}><View><Text style={st.kicker}>DRIVER SUPERAPP</Text><Text style={st.h1}>Where to?</Text></View><Pressable style={st.avatar} onPress={()=>setTab('profile')}><Text style={st.avatarText}>{(s.user.email??'U')[0].toUpperCase()}</Text></Pressable></View>
  {msg?<View style={st.noticeBox}><Text style={st.notice}>{msg}</Text></View>:null}
  {tab==='home'?<ScrollView contentContainerStyle={st.content}>
   <View style={st.map}><View style={st.mapGrid}/><View style={st.pin}/><Text style={st.mapLabel}>Addis Ababa</Text><View style={st.mapCard}><Text style={st.mapTitle}>Pickup area</Text><Text style={st.muted}>Live driver matching</Text></View></View>
   <View style={st.searchCard}><Text style={st.label}>PICKUP</Text><TextInput value={pickup} onChangeText={setPickup} placeholder="Choose pickup location" style={st.input}/><Text style={st.label}>DESTINATION</Text><TextInput value={drop} onChangeText={setDrop} placeholder="Where are you going?" style={st.input}/><Pressable disabled={busy} style={[st.btn,busy&&st.disabled]} onPress={requestRide}><Text style={st.white}>{busy?'Finding a driver…':'Request a ride'}</Text></Pressable></View>
   {trip?<View style={st.card}><View style={st.row}><Text style={st.title}>Current ride</Text><Text style={st.badge}>{trip.state.replace('_',' ')}</Text></View><Text style={st.muted}>{trip.pickup_label} → {trip.destination_label}</Text><Text style={st.amount}>{trip.total_minor?money(trip.total_minor):'Fare calculating'}</Text><Pressable style={st.outline} onPress={cancel}><Text style={st.outlineText}>Cancel ride</Text></Pressable></View>:null}
   <Text style={st.section}>Services</Text><View style={st.services}>{[['🚕','Ride','Everyday trips'],['📦','Delivery','Send anything'],['🏪','Business','Business orders']].map(x=><View key={x[1]} style={st.service}><Text style={st.icon}>{x[0]}</Text><Text style={st.title}>{x[1]}</Text><Text style={st.muted}>{x[2]}</Text></View>)}</View>
  </ScrollView>:tab==='trips'?<ScrollView contentContainerStyle={st.content}><Text style={st.section}>Your trips</Text>{history.map(x=><View style={st.card} key={x.id}><View style={st.row}><Text style={st.title}>{x.pickup_label??'Pickup'}</Text><Text style={st.badge}>{x.state}</Text></View><Text style={st.muted}>→ {x.destination_label??'Destination'}</Text>{x.total_minor?<Text style={st.amount}>{money(x.total_minor)}</Text>:null}</View>)}{!history.length?<Text style={st.muted}>No trips yet.</Text>:null}</ScrollView>:<ScrollView contentContainerStyle={st.content}><View style={st.card}><Text style={st.section}>Account</Text><Text style={st.muted}>{s.user.email??s.user.phone}</Text></View><View style={st.card}><Text style={st.section}>Payments</Text><Text style={st.muted}>Cash and supported digital payment methods will appear here.</Text></View><Pressable style={st.outline} onPress={()=>db.auth.signOut()}><Text style={st.outlineText}>Sign out</Text></Pressable></ScrollView>}
  <View style={st.tabs}>{[['home','Home'],['trips','Trips'],['profile','Profile']].map(x=><Pressable key={x[0]} style={st.tab} onPress={()=>setTab(x[0])}><Text style={[st.tabText,tab===x[0]&&st.active]}>{x[1]}</Text></Pressable>)}</View>
 </SafeAreaView>
}
const st=StyleSheet.create({screen:{flex:1,backgroundColor:BG},center:{flex:1,justifyContent:'center',padding:24,backgroundColor:BG},logo:{fontSize:12,fontWeight:'900',letterSpacing:2,color:TEAL},h1:{fontSize:30,fontWeight:'900',color:NAVY,marginTop:5},muted:{color:'#64748B',lineHeight:21},header:{backgroundColor:'#fff',padding:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.5,color:TEAL},avatar:{width:44,height:44,borderRadius:22,backgroundColor:NAVY,alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontWeight:'900'},content:{padding:16,paddingBottom:105,gap:14},map:{height:285,borderRadius:22,backgroundColor:'#DCE7E3',overflow:'hidden',position:'relative'},mapGrid:{position:'absolute',inset:0,opacity:.22,backgroundColor:'#AFC5BE'},pin:{position:'absolute',left:'48%',top:'44%',width:22,height:22,borderRadius:12,backgroundColor:TEAL,borderWidth:5,borderColor:'#fff'},mapLabel:{position:'absolute',top:18,left:18,fontWeight:'900',color:NAVY},mapCard:{position:'absolute',bottom:14,left:14,right:14,backgroundColor:'#fff',padding:14,borderRadius:15},mapTitle:{fontWeight:'900',color:NAVY},searchCard:{backgroundColor:'#fff',padding:16,borderRadius:20,gap:10},label:{fontSize:10,fontWeight:'900',letterSpacing:1.3,color:'#64748B'},input:{minHeight:50,borderWidth:1,borderColor:'#D7DEE5',borderRadius:13,paddingHorizontal:14,fontSize:16,color:NAVY},btn:{minHeight:52,borderRadius:14,backgroundColor:TEAL,alignItems:'center',justifyContent:'center',paddingHorizontal:16},white:{color:'#fff',fontWeight:'900'},disabled:{opacity:.5},noticeBox:{margin:12,padding:12,borderRadius:12,backgroundColor:'#DFFAF5'},notice:{color:TEAL,fontWeight:'800'},card:{backgroundColor:'#fff',padding:16,borderRadius:18,gap:9},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{fontSize:17,fontWeight:'900',color:NAVY},badge:{backgroundColor:'#E6F7F4',color:TEAL,paddingHorizontal:9,paddingVertical:5,borderRadius:9,fontWeight:'900',textTransform:'capitalize'},amount:{fontSize:22,fontWeight:'900',color:NAVY},outline:{minHeight:48,borderRadius:13,borderWidth:1,borderColor:'#CBD5E1',alignItems:'center',justifyContent:'center'},outlineText:{fontWeight:'900',color:NAVY},section:{fontSize:20,fontWeight:'900',color:NAVY},services:{flexDirection:'row',gap:10},service:{flex:1,backgroundColor:'#fff',borderRadius:16,padding:13,gap:5},icon:{fontSize:24},tabs:{position:'absolute',bottom:0,left:0,right:0,height:82,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#E2E8F0',flexDirection:'row',paddingBottom:10},tab:{flex:1,alignItems:'center',justifyContent:'center'},tabText:{fontWeight:'800',color:'#94A3B8'},active:{color:TEAL}});
