import React,{useEffect,useState}from'react';
import{Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View}from'react-native';
import{useLocalSearchParams,useRouter}from'expo-router';
import{createClient}from'@supabase/supabase-js';
const db=createClient(process.env.EXPO_PUBLIC_SUPABASE_URL??'',process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY??'');const NAVY='#0B1F33',TEAL='#0F766E',BG='#F6F8FA';
export default function Trip(){const router=useRouter();const{id}=useLocalSearchParams<{id:string}>();const[t,setT]=useState<any>(null),[msg,setMsg]=useState('');
useEffect(()=>{if(!id)return;load();const ch=db.channel('trip-'+id).on('postgres_changes',{event:'*',schema:'public',table:'trips',filter:'id=eq.'+id},load).subscribe();return()=>{db.removeChannel(ch)}},[id]);
async function load(){const{data,error}=await db.from('trips').select('id,state,pickup_label,destination_label,total_minor,driver_id').eq('id',id).single();if(error)setMsg(error.message);else setT(data)}
async function cancel(){const{error}=await db.from('trips').update({state:'cancelled'}).eq('id',id).in('state',['requested','accepted','arriving']);setMsg(error?.message??'Ride cancelled.');load()}
if(!t)return <SafeAreaView style={st.center}><Text style={st.title}>Loading trip…</Text>{msg?<Text>{msg}</Text>:null}</SafeAreaView>;
const terminal=['completed','cancelled','cancelled_by_customer','cancelled_by_driver','cancelled_by_system'].includes(t.state);
return <SafeAreaView style={st.screen}><ScrollView contentContainerStyle={st.content}><Pressable onPress={()=>router.replace('/')}><Text style={st.back}>‹ Home</Text></Pressable><View style={st.head}><View><Text style={st.kicker}>YOUR RIDE</Text><Text style={st.title}>{t.state.replaceAll('_',' ')}</Text></View><View style={st.dot}/></View><View style={st.map}><Text style={st.mapTitle}>Live trip</Text><Text style={st.muted}>Trip status updates in real time.</Text><View style={st.pin}/></View><View style={st.card}><Text style={st.label}>ROUTE</Text><Text style={st.place}>{t.pickup_label??'Pickup'}</Text><Text style={st.arrow}>↓</Text><Text style={st.place}>{t.destination_label??'Destination'}</Text></View><View style={st.card}><Text style={st.section}>{t.driver_id?'Driver assigned':'Finding your driver'}</Text><Text style={st.muted}>{t.driver_id?'Your verified driver and vehicle details will appear here.':'We are matching you with an available driver nearby.'}</Text></View><View style={st.status}><Text style={st.section}>Trip status</Text>{['requested','accepted','arriving','in_progress','completed'].map(x=><View key={x} style={st.step}><View style={[st.stepDot,t.state===x&&st.current]}/><Text style={[st.stepText,t.state===x&&st.currentText]}>{x.replaceAll('_',' ')}</Text></View>)}</View>{msg?<Text style={st.notice}>{msg}</Text>:null}{!terminal?<Pressable style={st.cancel} onPress={cancel}><Text style={st.cancelText}>Cancel ride</Text></Pressable>:<Pressable style={st.btn} onPress={()=>router.replace('/')}><Text style={st.white}>Back to home</Text></Pressable>}</ScrollView></SafeAreaView>}
const st=StyleSheet.create({screen:{flex:1,backgroundColor:BG},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:BG},content:{padding:18,gap:14},back:{color:TEAL,fontWeight:'900'},head:{backgroundColor:'#fff',borderRadius:18,padding:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.3,color:TEAL},title:{fontSize:27,fontWeight:'900',color:NAVY},dot:{width:12,height:12,borderRadius:6,backgroundColor:TEAL},map:{height:240,borderRadius:20,backgroundColor:'#DCE7E3',padding:18,position:'relative'},mapTitle:{fontSize:18,fontWeight:'900',color:NAVY},muted:{color:'#64748B',lineHeight:20},pin:{position:'absolute',left:'48%',top:'45%',width:24,height:24,borderRadius:12,backgroundColor:TEAL,borderWidth:5,borderColor:'#fff'},card:{backgroundColor:'#fff',borderRadius:18,padding:16,gap:8},label:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:'#64748B'},place:{fontSize:16,fontWeight:'800',color:NAVY},arrow:{color:TEAL,fontWeight:'900'},section:{fontSize:18,fontWeight:'900',color:NAVY},status:{backgroundColor:'#fff',borderRadius:18,padding:16,gap:11},step:{flexDirection:'row',alignItems:'center',gap:10},stepDot:{width:10,height:10,borderRadius:5,backgroundColor:'#CBD5E1'},current:{backgroundColor:TEAL},stepText:{color:'#64748B',fontWeight:'700',textTransform:'capitalize'},currentText:{color:NAVY,fontWeight:'900'},notice:{color:'#B45309',fontWeight:'800'},cancel:{minHeight:52,borderRadius:14,borderWidth:1,borderColor:'#FCA5A5',alignItems:'center',justifyContent:'center'},cancelText:{color:'#B91C1C',fontWeight:'900'},btn:{minHeight:52,borderRadius:14,backgroundColor:TEAL,alignItems:'center',justifyContent:'center'},white:{color:'#fff',fontWeight:'900'}});
